class RegisterRequestModel {
  int userTypeId;
  String firmName;
  String gstNo;
  String valid;
  String phoneNo;
  String dl1;
  String dl2;
  String pic3;
  String address;
  String registerDate;
  int payLateStatus;
  String email;
  String postalCode;
  String dlNo;
  int adminId;
  int completeRegStatus;
  int countryId;
  int stateId;
  int cityId;
  int regionalId;
  int areaId;
  int status;
  String dlName;
  String fssaiNo;
  String personName;
  String personNumber;
  String alternateNumber;
  int hdnDrugYesNo;
  int hdnFSSAI;
  int gstNoYesNo;
  int mrid;
  String terms;
  String firmPassword;
  int appStatus;
  int salePid;
  int salesExecutiveId;

  RegisterRequestModel({
    required this.userTypeId,
    required this.firmName,
    required this.gstNo,
    required this.valid,
    required this.phoneNo,
    required this.dl1,
    required this.dl2,
    required this.pic3,
    required this.address,
    required this.registerDate,
    required this.payLateStatus,
    required this.email,
    required this.postalCode,
    required this.dlNo,
    required this.adminId,
    required this.completeRegStatus,
    required this.countryId,
    required this.stateId,
    required this.cityId,
    required this.regionalId,
    required this.areaId,
    required this.status,
    required this.dlName,
    required this.fssaiNo,
    required this.personName,
    required this.personNumber,
    required this.alternateNumber,
    required this.hdnDrugYesNo,
    required this.hdnFSSAI,
    required this.gstNoYesNo,
    required this.mrid,
    required this.terms,
    required this.firmPassword,
    required this.appStatus,
    required this.salePid,
    required this.salesExecutiveId,
  });

  Map<String, String> toMap() {
    return {
      "user_type_id": userTypeId.toString(),
      "firm_name": firmName,
      "gstno": gstNo,
      "valid": valid,
      "phoneno": phoneNo,
      "dl1": dl1,
      "dl2": dl2,
      "pic3": pic3,
      "address": address,
      "register_date": registerDate,
      "pay_late_status": payLateStatus.toString(),
      "txtemail": email,
      "txtpostalcode": postalCode,
      "txtdlno": dlNo,
      "AdminId": adminId.toString(),
      "complete_reg_status": completeRegStatus.toString(),
      "countryid": countryId.toString(),
      "stateid": stateId.toString(),
      "cityid": cityId.toString(),
      "Regionalid": regionalId.toString(),
      "Areaid": areaId.toString(),
      "Status": status.toString(),
      "txtdlname": dlName,
      "fssaiNo": fssaiNo,
      "PersonName": personName,
      "PersonNumber": personNumber,
      "AlternateNumber": alternateNumber,
      "hdnDrugsyesno": hdnDrugYesNo.toString(),
      "hdnFSSAI": hdnFSSAI.toString(),
      "gstnoyesno": gstNoYesNo.toString(),
      "mrid": mrid.toString(),
      "hftermsandconditions": terms,
      "firmpassword": firmPassword,
      "app_status": appStatus.toString(),
      "salepid": salePid.toString(),
      "SalesexecutiveId": salesExecutiveId.toString(),
    };
  }
}