import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class ReturnExchange extends StatelessWidget {
  const ReturnExchange({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: Colors.blue,
        iconTheme: const IconThemeData(color: Colors.white),
        title: Text(
          "Return & Exchange",
          style: GoogleFonts.poppins(color: Colors.white),
        ),
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [

              // const PolicySection(
              //   title: "",
              //   text: "Updated at 2022-03-01",
              // ),
              //
              // const SizedBox(height: 12),

              Material(
                elevation: 4,
                borderRadius: BorderRadius.circular(12),
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(12),
                  child: Image.asset(
                    "assets/medicine/return.png",
                    height: 180,
                    width: double.infinity,
                    fit: BoxFit.cover,
                  ),
                ),
              ),

              const SizedBox(height: 20),

              const PolicySection(
                title: "Definitions and key terms",
                text:
                "To help explain things as clearly as possible in this Return & Refund Policy, every time any of these terms are referenced, are strictly defined as:\n"
                    "Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.\n"
                    "Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to medrpha.\n"
                    "Customer: refers to the company, organization or person that signs up to use the medrpha Service.\n"
                    "Device: any internet connected device such as a phone, tablet, computer.\n"
                    "Service: refers to the service provided by medrpha.\n"
                    "Website: medrpha.com\n"
                    "You: a person or entity registered with medrpha.",
              ),

              const SizedBox(height: 20),

              const PolicySection(
                title: "Return & Refund Policy",
                text:
                "Thanks for shopping at Medrpha. We appreciate that you like to buy our products. "
                    "If there is any issue with the product/service, you have 1 week to request a refund. "
                    "Product must be damage-free, otherwise refund will be cancelled.",
              ),
              const SizedBox(height: 12),

              Material(
                elevation: 4,
                borderRadius: BorderRadius.circular(12),
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(12),
                  child: Image.asset(
                    "assets/medicine/refund.png",
                    height: 180,
                    width: double.infinity,
                    fit: BoxFit.cover,
                  ),
                ),
              ),

              const SizedBox(height: 20),
              const PolicySection(
                title: "Refunds",
                text: "We at  ourselves to serving our customers with the best products. Every single product that you choose is thoroughly inspected, checked for defects and packaged with utmost care. We do this to ensure that you fall in love with our products.\n"
                    "Sadly, there are times when we may not have the product(s) that you choose in stock, or may face some issues with our inventory and quality check. In such cases, we may have to cancel your order. You will be intimated about it in advance so that you don't have to worry unnecessarily about your order. If you have purchased via Online payment (not Cash on Delivery), then you will be refunded once our team confirms your request.\n"
                    "We carry out thorough quality check before processing the ordered item. We take utmost care while packing the product. At the same time we ensure that the packing is good such that the items won’t get damaged during transit. Please note that medrpha is not liable for damages that are caused to the items during transit or transportation.\n"
                    "We will revise your returned product as soon as we receive it and if it follows the guidelines addressed above, we will proceed to issue a refund of your purchase. Your refund may take a couple of days to process but you will be notified when you receive your money.",
              ),
              const SizedBox(height: 20),
              const PolicySection(title: "Shipping",
                  text: "medrpha is not responsible for return shipping costs. Every shipping has to be paid by the customer, even if the item had free shipping in the first place, the customer has to pay for the shipping in return."),
              const SizedBox(height: 12),

              Material(
                elevation: 4,
                borderRadius: BorderRadius.circular(12),
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(12),
                  child: Image.asset(
                    "assets/medicine/shipping.png",
                    height: 180,
                    width: double.infinity,
                    fit: BoxFit.cover,
                  ),
                ),
              ),
              const SizedBox(height: 20,),
              const PolicySection(title: "Your Consent",
                  text: "By using our website/app, registering an account, or making a purchase, you hereby consent to our Return & Refund Policy and agree to its terms."),
              const SizedBox(height: 20,),
              const PolicySection(title: "Changes To Our Return & Refund Policy",
                  text:"Should we update, amend or make any changes to this document so that they accurately reflect our Service and policies. Unless otherwise required by law, those changes will be prominently posted here. Then, if you continue to use the Service, you will be bound by the updated Return & Refund Policy. If you do not want to agree to this or any updated Return & Refund Policy, you can delete your account."),


            ],
          ),
        ),
      ),

    );
  }
}


/// Reusable widget (same as AboutUs style)
class PolicySection extends StatelessWidget {
  final String title;
  final String text;

  const PolicySection({
    super.key,
    required this.title,
    required this.text,
  });

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [

        // ✅ Only show title if not empty
        if (title.isNotEmpty) ...[
          Text(
            title,
            style: GoogleFonts.poppins(
              fontSize: 20,   // smaller = better
              fontWeight: FontWeight.w600,
              color: Colors.grey[800],
            ),
          ),
          const SizedBox(height: 8),
        ],

        Text(
          text,
          style:GoogleFonts.poppins(
            fontSize: 15,
            height: 1.6,
          ),
        )
      ],
    );
  }
}
